---
- name: Check RHEL8 and Tower version dependency
  assert:
    that:
      - deploy_tower_tower_version is version('3.5.0', '>=')
  when: deploy_tower_rhel_major_version >= 8

# see also: https://releases.ansible.com/ansible-tower/setup-bundle/
- name: Ensure right path depended with a version is give
  set_fact:
    deploy_tower_installer_version: "{{ deploy_tower_installer_version | regex_replace('.el\\d', '') }}"
  when: deploy_tower_tower_version is version('3.6.2', '>=')

- name: Ensure install directory is exsisting
  file:
    state: directory
    path: "{{ deploy_tower_install_dir }}"
